### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by awatson1978** [awatson1978/ckcc#76]
Do we like this layout?  This is what two focus groups from the Pharma industry came up with.

![screen shot 2015-10-12 at 8 53 38 pm](https://cloud.githubusercontent.com/assets/675910/10445125/6bf58732-7123-11e5-9421-49133da1fbb3.png)

**Comment by tedgoldstein** [comment]
Great start. Very Cool. Must make it extensible. 

Think apps. We will have many apps. A given user will have 20 apps out of thousands of apps.

**Comment by awatson1978** [comment]
:nods:  
Understood about extensible.  Not 100% sure how that's going to eventually turn out (re:  menu bar vs modal vs navigation page); but we can make sure to implement this in such a way that it doesn't lock us into a single approach.

**Comment by awatson1978** [comment]
https://dcc.icgc.org/projects
https://icgc.org/
http://www.cbioportal.org/

**Comment by awatson1978** [comment]
aeed6833791b051885adef03927bdc947249a224
